---
title: "Field training 02 - Leaf traits measurements"
subtitle: "Documentation"
subsubtitle: "Leaf traits measurements"
author: "Denis Streitmatter"
date: last-modified
format:
    pdf:
        documentclass: scrreport
        theme: united
        toc: true
        toc-depth: 2
        number-sections: true
        number-depth: 1
        toc-title: Table of Contents
        toc-location: body
        colorlinks: true
header-includes:  
- \usepackage{graphicx}
- \usepackage{lscape}
- \usepackage{array}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
{{< pagebreak >}}

# Task 1: Leaf sampling

## Procedure

Date: 16.05.2023

Group-ID: 4

Participants: Denis, Fabian, Louis, Lukas, Marie-Louise, Maxwell 

Coordinates: 51.332222, 12.384167

Material used:

- Smartphone (GPS + plant species determination)
- Book (Flora Vegetativa)
- Survey sheet



{{< pagebreak >}}

## Leaf images

{{< pagebreak >}}

## Recorded species tables




{{< pagebreak >}}

<!--
Table in landscape format (uncomment if needed)

# landscape table format (better?)

::::::::{.landscape data-latex=""}

\begin{table}[]
\fontsize{22}{\baselineskip}\selectfont
\renewcommand{\arraystretch}{4}
\resizebox{\columnwidth}{!}{%
\begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
\hline
\textbf{Group-ID} &
  \textbf{Plot-ID} &
  \textbf{Subplot-ID} &
  \textbf{Date} &
  \textbf{\begin{tabular}[c]{@{}c@{}}X-Coordinate \\ center\end{tabular}} &
  \textbf{\begin{tabular}[c]{@{}c@{}}Y-Coordinate \\ center\end{tabular}} &
  \textbf{Litter / \%} &
  \textbf{Soil / \%} &
  \textbf{Water / \%} &
  \textbf{Moss / \%} &
  \textbf{Height / cm} &
  \textbf{\begin{tabular}[c]{@{}c@{}}Acer \\ platanoides\end{tabular}} &
  \textbf{\begin{tabular}[c]{@{}c@{}}Achillea \\ millefolium\end{tabular}} &
  \textbf{\begin{tabular}[c]{@{}c@{}}Bellis \\ perennis\end{tabular}} &
  \textbf{\begin{tabular}[c]{@{}c@{}}Capsella \\ bursa-pastoris\end{tabular}} &
  \textbf{\begin{tabular}[c]{@{}c@{}}Dactylis \\ glomerata\end{tabular}} &
  \textbf{\begin{tabular}[c]{@{}c@{}}Elymus \\ repens\end{tabular}} &
  \textbf{\begin{tabular}[c]{@{}c@{}}Geranium \\ molle\end{tabular}} &
  \textbf{\begin{tabular}[c]{@{}c@{}}Geranium \\ pusillum\end{tabular}} &
  \textbf{\begin{tabular}[c]{@{}c@{}}Lolium \\ perenne\end{tabular}} &
  \textbf{\begin{tabular}[c]{@{}c@{}}Poa \\ annua\end{tabular}} &
  \textbf{\begin{tabular}[c]{@{}c@{}}Polygonum \\ aviculare\end{tabular}} &
  \textbf{\begin{tabular}[c]{@{}c@{}}Trifolium \\ repens\end{tabular}} &
  \textbf{\begin{tabular}[c]{@{}c@{}}Veronica \\ arvensis\end{tabular}} \\ \hline
4 & 1 & 1 & 16.05.2023 & 51.332222 & 12.384167 & 1.5 & 11 & 0 & 8 & 6 &     &     & 15 & 4 &   & 2  & 15 & 1 & 50 & 10 & 0.5 & 10 & 1   \\ \hline
4 & 1 & 2 & 16.05.2023 &           &           & 1   & 4  & 0 & 1 & 6 &     & 0.5 & 22 &   & 2 &    & 18 & 1 & 55 & 15 & 0.5 &    & 1   \\ \hline
4 & 1 & 3 & 16.05.2023 &           &           & 1   & 3  & 0 & 2 & 6 & 0.5 & 3   & 8  &   &   & 1  & 19 &   & 38 & 19 &     & 18 & 0.5 \\ \hline
4 & 1 & 4 & 16.05.2023 &           &           & 1   & 10 & 0 & 1 & 4 &     &     & 6  &   &   & 15 & 17 &   & 28 & 10 & 0.5 & 1  & 2   \\ \hline
\end{tabular}%
}
\caption{Subplot x species table for the recorded herbaceous vegetation. The values are the cover fraction of the total plot in {[}\%{]}.}
\end{table}
::::::::

-->

# Task 4: Leaf area measurement

In the next step, we determined the mass per leaf area. We took the sheets out of the paper bag and placed them one by one into the sheet scanner. We had to make sure that the sheets were fully spread out, did not overlap, and were within the measurement range area. For some sheets, the scanner was not large enough to measure all 10 sheets at once. So we did multiple scans and added up and documented the measured leaf area for each species.  

To check the correctness of the scanner we performed a second type of leaf surface measurement. For this, we placed the leaves on a DinA4 sheet and took a photo. We wrote a small script to convert the scans of sheets and paper into black and white images and calculate the cumulative sheet area from the proportion of black pixels of the total paper area. Then we compared the measured area with the result of the sheet scanner. They were very similar everywhere with slight variations (see documentation).  
There were two different approaches for measuring the leaf area: Using a specific tool or calculating it on the base of photos of the leafs on standardised A4 paper sheets

## Photo-based approach 

For the photo-based approach we preprocessed the photos with the image-software `gimp` and then calculated the leaf size with a [python script](https://github.com/yum-yab/ground_truthing_module/blob/main/leaf_area_measure/leaf_area_measurement.py).

### Preprocessing of the Photos

The goal of this step is to reduce the image to the necessary parts, mainly cutting out the A4 paper sheet. For this a few steps were used:

1. Load the image in gimp
2. Use the `lasso-select tool` for selecting the corners of the A4 paper
3. Press `CTRL + i` for inverting the selection
4. Press `CTRL + x` for cutting out everything thats not on the paper
5. Use `Image > Crop to content` to reduce the image size
    - this step is optional since alpha channel (= transparency) is ignored in the script, but this reduces file size and therefor makes it a bit faster
6. Save images in proper format for script:
    - Name of the file `{leaf-number}_someuniquename_{double}.jpg` (only use `double` if two A4 papers were used)
    - save all files of one species in one directory

### Calculating the leaf size

The code and the description how to use it can be found in [this git repository](https://github.com/yum-yab/ground_truthing_module/blob/main/leaf_area_measure/). 
Here we will only describe the main ideas of the process. 
In general we know the area 

First of all we hardcoded some values: The **A4 area** for reference, 

## LMA

To calculate the biomass of the sheets, we now had to determine the dry weight of the sheets. To do this, we put the leaves back in the paper bag, and put them in the drying oven at 50 - 55 °C. The samples were dried for 72h. Then we measured the dry weight and noted the values. Finally we calculated the ratio of dry weight to leaf area in mg/cm², which is the Leaf mass per Aria (LMA).  

# Woody vegetation sampling

## Procedure

Date: 16.05.2023

Group-ID: 4

Participants: Dennis, Fabian, Louis, Lukas, Marie-Louise, Maxwell 

Coordinates: 51.332222, 12.384167

Material used: 

- Quadrant
- Tape (for distance and diameter measurements)
- Smartphone (GPS + tree species determination)
- Survey sheet

Woody vegetation was surveyed using the 'point centered quarter method' (PCQM) on May 16th, 2023. This method is used to estimate plant abundance by placing a cross at a random location and assessing tree traits of the nearest tree in each quadrant. The data also serve as ground truthing data for 5x5 meter satellite images and are intended to represent species composition of the tree layer in described park area. 
For this purpose we selected again a random point by throwing a pile in the air and noted down the metadata, i.e. date and coordinates in LatLong/WGS84 format using a smartphone. No explicit photos of the recorded location nor trees were taken.
In order to record the tree layer using the PCQM, we identified the nearest tree in each quadrant using a tape for the distance measure and knowledge as well as the software 'FloraIncognita' to determine the species. The nearest species were named Acer platanoides, Acer pseudoplatanus, Cornus sanguinea and Quercus robur. For each tree, the distance from the determined center location and the girth at breast height (~130cm) [cm] were measured with a tape. The diameter at breast height [cm] was then calculated with $\frac{girth [cm]}{\pi}$. Based on the diameter, the basal area [$\text{cm}^2$] was calculated with the formula $\pi \text{r}^2$, with $r = \frac{diameter [cm]}{2} [cm]$.
Afterwards, the recorded data as well as the metadata were entered in a GoogleDocs sheet, which can be see in Table 2.1.


{{< pagebreak >}}

## Recorded species table

\begin{table}[h!]
\fontsize{32}{\baselineskip}\selectfont
\renewcommand{\arraystretch}{8}
\resizebox{\columnwidth}{!}{%
\begin{tabular}{|l|l|l|l|l|l|l|l|l|l|l|l|}
\hline
\textbf{Group-ID} &
  \textbf{Plot-ID} &
  \textbf{Tree-ID} &
  \textbf{Date} &
  \textbf{\begin{tabular}[c]{@{}l@{}}X-Coordinate\\ center\end{tabular}} &
  \textbf{\begin{tabular}[c]{@{}l@{}}Y-Coordinate\\ center\end{tabular}} &
  \textbf{Species} &
  \textbf{Distance} &
  \textbf{Girth (cm)} &
  \textbf{DBH / cm} &
  \textbf{BA / cm²} &
  \textbf{total BA / cm²} \\ \hline
4 & 1 & 1 & 16.05.2023 & 51.332222 & 12.384167 & Acer platanoides    & 9.8  & 239 & 76.08 & 4545.54 & 4545.54 \\ \hline
4 & 1 & 2 & 16.05.2023 &           &           & Acer pseudoplatanus & 10.9 & 205 & 65.25 & 3344.24 & 3344.24 \\ \hline
4 & 1 & 3 & 16.05.2023 &           &           & Cornus sanguinea    & 15.7 & 36  & 11.46 & 103.13  & 103.13  \\ \hline
4 & 1 & 4 & 16.05.2023 &           &           & Quercus robur       & 25.2 & 302 & 96.13 & 7257.78 & 7257.78 \\ \hline
\end{tabular}%
}
\caption{Table for the recorded woody vegetation including metadata.}
\end{table}
